"""
NCAAB (Men's NCAA Basketball) team alias table.

Maps every reasonable variant of a team name → the canonical form used by
The Odds API. Keys must be lowercase. Values match Odds API exactly.

Two layers per team:
    1. Bare school name (e.g. "alabama") — anchor for _strip_college_nickname()
       when walking "Alabama Crimson Tide" → "Alabama Crimson" → "Alabama"
    2. Full Odds API "School Nickname" form (e.g. "alabama crimson tide")

When adding a new team: add BOTH the bare name AND the "bare name + nickname"
full form. Run `python main.py --date <date> --debug` to find missing entries.

NOTE: This file is fully independent from wncaab.py. If a school appears in
both men's and women's tournaments, it must be entered in both files separately.
"""

ALIASES: dict[str, str] = {
    # ── Power conferences ────────────────────────────────────────────────────
    "alabama": "Alabama",
    "alabama crimson tide": "Alabama",
    "arizona": "Arizona",
    "arizona wildcats": "Arizona",
    "arizona st": "Arizona St",
    "arizona state": "Arizona St",
    "arizona state sun devils": "Arizona St",
    "arkansas": "Arkansas",
    "arkansas razorbacks": "Arkansas",
    "auburn": "Auburn",
    "auburn tigers": "Auburn",
    "baylor": "Baylor",
    "baylor bears": "Baylor",
    "ball state": "Ball State",
    "ball state cardinals": "Ball State",
    "byu": "BYU",
    "brigham young": "BYU",
    "brigham young cougars": "BYU",
    "cincinnati": "Cincinnati",
    "cincinnati bearcats": "Cincinnati",
    "clemson": "Clemson",
    "clemson tigers": "Clemson",
    "colorado": "Colorado",
    "colorado buffaloes": "Colorado",
    "creighton": "Creighton",
    "creighton bluejays": "Creighton",
    "davidson": "Davidson",
    "davidson wildcats": "Davidson",
    "dayton": "Dayton",
    "dayton flyers": "Dayton",
    "depaul": "DePaul",
    "depaul blue demons": "DePaul",
    "duke": "Duke",
    "duke blue devils": "Duke",
    "duquesne": "Duquesne",
    "duquesne dukes": "Duquesne",
    "florida": "Florida",
    "florida gators": "Florida",
    "florida st": "Florida St",
    "florida state": "Florida St",
    "florida state seminoles": "Florida St",
    "georgetown": "Georgetown",
    "georgetown hoyas": "Georgetown",
    "georgia": "Georgia",
    "georgia bulldogs": "Georgia",
    "georgia tech": "Georgia Tech",
    "georgia tech yellow jackets": "Georgia Tech",
    "gonzaga": "Gonzaga",
    "gonzaga bulldogs": "Gonzaga",
    "howard": "Howard",
    "howard bison": "Howard",
    "illinois": "Illinois",
    "illinois fighting illini": "Illinois",
    "illinois illini": "Illinois",
    "illinois state": "Illinois State",
    "illinois st": "Illinois State",
    "ilst": "Illinois State",
    "illinois state redbirds": "Illinois State",
    "illinois st redbirds": "Illinois State",
    "indiana": "Indiana",
    "indiana hoosiers": "Indiana",
    "iowa": "Iowa",
    "iowa hawkeyes": "Iowa",
    "iowa st": "Iowa State",
    "iowa st.": "Iowa State",
    "iowa state": "Iowa State",
    "iowa state cyclones": "Iowa State",
    "iowa st cyclones": "Iowa State",
    "kansas": "Kansas",
    "kansas jayhawks": "Kansas",
    "kansas st": "Kansas St",
    "kansas state": "Kansas St",
    "kansas state wildcats": "Kansas St",
    "kentucky": "Kentucky",
    "kentucky wildcats": "Kentucky",
    "louisville": "Louisville",
    "louisville cardinals": "Louisville",
    "lsu": "LSU",
    "lsu tigers": "LSU",
    "marquette": "Marquette",
    "marquette golden eagles": "Marquette",
    "maryland": "Maryland",
    "maryland terrapins": "Maryland",
    "memphis": "Memphis",
    "memphis tigers": "Memphis",
    "miami": "Miami FL",
    "miami fl": "Miami FL",
    "miami hurricanes": "Miami FL",
    "miami (fl)": "Miami FL",
    "miami (florida) hurricanes": "Miami FL",
    "miami oh": "Miami OH",
    "miami (oh)": "Miami OH",
    "miami (ohio) redhawks": "Miami OH",
    "michigan": "Michigan",
    "michigan wolverines": "Michigan",
    "michigan st": "Michigan St",
    "michigan state": "Michigan St",
    "michigan state spartans": "Michigan St",
    "michigan st spartans": "Michigan St",
    "minnesota": "Minnesota",
    "minnesota golden gophers": "Minnesota",
    "mississippi st": "Mississippi St",
    "mississippi state": "Mississippi St",
    "mississippi state bulldogs": "Mississippi St",
    "nc state": "NC State",
    "nc st": "NC State",
    "ncst": "NC State",
    "n.c. state": "NC State",
    "north carolina state": "NC State",
    "north carolina state wolfpack": "NC State",
    "nc state wolfpack": "NC State",
    "north carolina": "North Carolina",
    "north carolina tar heels": "North Carolina",
    "unc": "North Carolina",
    "unc tar heels": "North Carolina",
    "notre dame": "Notre Dame",
    "notre dame fighting irish": "Notre Dame",
    "ohio st": "Ohio St",
    "ohio st.": "Ohio St",
    "ohio state": "Ohio St",
    "ohio state buckeyes": "Ohio St",
    "ohio st buckeyes": "Ohio St",
    "oklahoma": "Oklahoma",
    "oklahoma sooners": "Oklahoma",
    "oregon": "Oregon",
    "oregon ducks": "Oregon",
    "penn st": "Penn St",
    "penn state": "Penn St",
    "penn state nittany lions": "Penn St",
    "pittsburgh": "Pittsburgh",
    "pittsburgh panthers": "Pittsburgh",
    "portland": "Portland",
    "portland pilots": "Portland",
    "purdue": "Purdue",
    "purdue boilermakers": "Purdue",
    "rutgers": "Rutgers",
    "rutgers scarlet knights": "Rutgers",
    "seton hall": "Seton Hall",
    "seton hall pirates": "Seton Hall",
    "st. john's": "St. John's",
    "st. john's red storm": "St. John's",
    "syracuse": "Syracuse",
    "syracuse orange": "Syracuse",
    "tcu": "TCU",
    "tcu horned frogs": "TCU",
    "temple": "Temple",
    "temple owls": "Temple",
    "tennessee": "Tennessee",
    "tennessee volunteers": "Tennessee",
    "texas": "Texas",
    "texas longhorns": "Texas",
    "texas am": "Texas A&M",
    "texas a&m": "Texas A&M",
    "texas a&m aggies": "Texas A&M",
    "texas tech": "Texas Tech",
    "texas tech red raiders": "Texas Tech",
    "tulsa": "Tulsa",
    "tulsa golden hurricane": "Tulsa",
    "ucla": "UCLA",
    "ucla bruins": "UCLA",
    "usc": "USC",
    "usc trojans": "USC",
    "utah": "Utah",
    "utah utes": "Utah",
    "vanderbilt": "Vanderbilt",
    "vanderbilt commodores": "Vanderbilt",
    "villanova": "Villanova",
    "villanova wildcats": "Villanova",
    "virginia": "Virginia",
    "virginia cavaliers": "Virginia",
    "virginia tech": "Virginia Tech",
    "virginia tech hokies": "Virginia Tech",
    "wake forest": "Wake Forest",
    "wake forest demon deacons": "Wake Forest",
    "washington": "Washington",
    "washington huskies": "Washington",
    "wichita st": "Wichita St",
    "wichita state": "Wichita St",
    "wichita state shockers": "Wichita St",
    "wisconsin": "Wisconsin",
    "wisconsin badgers": "Wisconsin",
    "xavier": "Xavier",
    "xavier musketeers": "Xavier",
    # ── Mid-majors / conference tournament regulars ──────────────────────────
    "akron": "Akron",
    "akron zips": "Akron",
    "alabama a&m": "Alabama A&M",
    "alabama a&m bulldogs": "Alabama A&M",
    "cal state fullerton": "Cal State Fullerton",
    "csu fullerton": "Cal State Fullerton",
    "csu fullerton titans": "Cal State Fullerton",
    "cal state northridge": "Cal State Northridge",
    "csu northridge": "Cal State Northridge",
    "csu northridge matadors": "Cal State Northridge",
    "csun": "Cal State Northridge",
    "california baptist": "California Baptist",
    "cal baptist": "California Baptist",
    "cal baptist lancers": "California Baptist",
    "california": "California Golden Bears",
    "cal": "California Golden Bears",
    "cal bears": "California Golden Bears",
    "california golden bears": "California Golden Bears",
    "charlotte": "Charlotte 49ers",
    "charlotte 49ers": "Charlotte 49ers",
    "delaware st": "Delaware St",
    "delaware state": "Delaware St",
    "delaware st hornets": "Delaware St",
    "drake": "Drake",
    "florida a&m": "Florida A&M",
    "florida a&m rattlers": "Florida A&M",
    "george washington": "George Washington",
    "gw": "George Washington",
    "gw revolutionaries": "George Washington",
    "george washington colonials": "George Washington",
    "hawaii": "Hawaii",
    "hawai'i": "Hawaii",
    "hawaii warriors": "Hawaii",
    "hawai'i rainbow warriors": "Hawaii",
    "houston": "Houston",
    "houston cougars": "Houston",
    "kent st": "Kent St",
    "kent state": "Kent St",
    "kent state golden flashes": "Kent St",
    "kent st golden flashes": "Kent St",
    "kennesaw st": "Kennesaw St",
    "kennesaw state": "Kennesaw St",
    "kennesaw st owls": "Kennesaw St",
    "louisiana tech": "Louisiana Tech",
    "louisiana tech bulldogs": "Louisiana Tech",
    "massachusetts": "UMass",
    "umass": "UMass",
    "umass minutemen": "UMass",
    "massachusetts minutemen": "UMass",
    "missouri st": "Missouri St",
    "missouri state": "Missouri St",
    "missouri state bears": "Missouri St",
    "missouri st bears": "Missouri St",
    "nebraska": "Nebraska",
    "nebraska cornhuskers": "Nebraska",
    "nevada": "Nevada",
    "nevada wolf pack": "Nevada",
    "new mexico": "New Mexico",
    "new mexico lobos": "New Mexico",
    "north carolina central": "North Carolina Central",
    "north carolina central eagles": "North Carolina Central",
    "north texas": "North Texas",
    "north texas mean green": "North Texas",
    "ohio": "Ohio",
    "ohio bobcats": "Ohio",
    "ole miss": "Ole Miss",
    "ole miss rebels": "Ole Miss",
    "prairie view a&m": "Prairie View A&M",
    "prairie view panthers": "Prairie View A&M",
    "prairie view a&m panthers": "Prairie View A&M",
    "rhode island": "Rhode Island",
    "saint joseph's": "Saint Joseph's",
    "saint joseph's hawks": "Saint Joseph's",
    "saint louis": "Saint Louis",
    "saint louis billikens": "Saint Louis",
    "saint mary's": "Saint Mary's",
    "sam houston": "Sam Houston",
    "sam houston bearkats": "Sam Houston",
    "sam houston st bearkats": "Sam Houston",
    "san diego st": "San Diego St",
    "san diego state": "San Diego St",
    "san diego st aztecs": "San Diego St",
    "south carolina st": "South Carolina St",
    "south carolina state": "South Carolina St",
    "south carolina st bulldogs": "South Carolina St",
    "south florida": "South Florida",
    "southern": "Southern",
    "southern jaguars": "Southern",
    "southern university": "Southern",
    "southern university jaguars": "Southern",
    "st. bonaventure": "St. Bonaventure",
    "st. bonaventure bonnies": "St. Bonaventure",
    "toledo": "Toledo",
    "toledo rockets": "Toledo",
    "tulane": "Tulane",
    "tulane green wave": "Tulane",
    "uc irvine": "UC Irvine",
    "uc irvine anteaters": "UC Irvine",
    "uic": "UIC Flames",
    "uic flames": "UIC Flames",
    "illinois chicago": "UIC Flames",
    "illinois-chicago": "UIC Flames",
    "ui chicago": "UIC Flames",
    "uc san diego": "UC San Diego",
    "uc san diego tritons": "UC San Diego",
    "ucf": "UCF",
    "ucf knights": "UCF",
    "uab": "UAB",
    "uab blazers": "UAB",
    "uconn": "UConn",
    "uconn huskies": "UConn",
    "connecticut huskies": "UConn",
    "ut arlington": "UT Arlington",
    "ut-arlington": "UT Arlington",
    "ut-arlington mavericks": "UT Arlington",
    "utsa": "UTSA",
    "utsa roadrunners": "UTSA",
    "rice": "Rice",
    "rice owls": "Rice",
    "utah st": "Utah St",
    "utah st.": "Utah St",
    "utah state": "Utah St",
    "utah state aggies": "Utah St",
    "utah st aggies": "Utah St",
    "utah tech": "Utah Tech",
    "utah tech trailblazers": "Utah Tech",
    "utah valley": "Utah Valley",
    "utah valley wolverines": "Utah Valley",
    "vcu": "VCU",
    "vcu rams": "VCU",
}
