"""
WNCAAB (Women's NCAA Basketball) team alias table.

Fully independent from ncaab.py — entries are duplicated intentionally so
that each file can evolve separately as rosters, conferences, and Kalshi/Odds
API naming conventions diverge between the men's and women's tournaments.

Keys must be lowercase. Values match The Odds API exactly.

Two layers per team:
    1. Bare school name — anchor for _strip_college_nickname()
    2. Full Odds API "School Nickname" form

Run `python main.py --date <date> --debug` to find missing entries.
"""

ALIASES: dict[str, str] = {
    # ── Power conferences ────────────────────────────────────────────────────
    "alabama": "Alabama",
    "alabama crimson tide": "Alabama",
    "arizona": "Arizona",
    "arizona wildcats": "Arizona",
    "arizona st": "Arizona St",
    "arizona state": "Arizona St",
    "arizona state sun devils": "Arizona St",
    "arkansas": "Arkansas",
    "arkansas razorbacks": "Arkansas",
    "auburn": "Auburn",
    "auburn tigers": "Auburn",
    "baylor": "Baylor",
    "baylor bears": "Baylor",
    "byu": "BYU",
    "brigham young": "BYU",
    "brigham young cougars": "BYU",
    "cincinnati": "Cincinnati",
    "cincinnati bearcats": "Cincinnati",
    "clemson": "Clemson",
    "clemson tigers": "Clemson",
    "colorado": "Colorado",
    "colorado buffaloes": "Colorado",
    "creighton": "Creighton",
    "creighton bluejays": "Creighton",
    "davidson": "Davidson",
    "davidson wildcats": "Davidson",
    "dayton": "Dayton",
    "dayton flyers": "Dayton",
    "depaul": "DePaul",
    "depaul blue demons": "DePaul",
    "duke": "Duke",
    "duke blue devils": "Duke",
    "florida": "Florida",
    "florida gators": "Florida",
    "florida st": "Florida St",
    "florida state": "Florida St",
    "florida state seminoles": "Florida St",
    "georgetown": "Georgetown",
    "georgetown hoyas": "Georgetown",
    "georgia": "Georgia",
    "georgia bulldogs": "Georgia",
    "georgia tech": "Georgia Tech",
    "georgia tech yellow jackets": "Georgia Tech",
    "gonzaga": "Gonzaga",
    "gonzaga bulldogs": "Gonzaga",
    "illinois": "Illinois",
    "illinois fighting illini": "Illinois",
    "illinois illini": "Illinois",
    "illinois state": "Illinois State",
    "illinois st": "Illinois State",
    "ilst": "Illinois State",
    "illinois state redbirds": "Illinois State",
    "illinois st redbirds": "Illinois State",
    "indiana": "Indiana",
    "indiana hoosiers": "Indiana",
    "iowa": "Iowa",
    "iowa hawkeyes": "Iowa",
    "iowa st": "Iowa State",
    "iowa st.": "Iowa State",
    "iowa state": "Iowa State",
    "iowa state cyclones": "Iowa State",
    "iowa st cyclones": "Iowa State",
    "kansas": "Kansas",
    "kansas jayhawks": "Kansas",
    "kansas st": "Kansas St",
    "kansas state": "Kansas St",
    "kansas state wildcats": "Kansas St",
    "kentucky": "Kentucky",
    "kentucky wildcats": "Kentucky",
    "louisville": "Louisville",
    "louisville cardinals": "Louisville",
    "lsu": "LSU",
    "lsu tigers": "LSU",
    "marquette": "Marquette",
    "marquette golden eagles": "Marquette",
    "maryland": "Maryland",
    "maryland terrapins": "Maryland",
    "miami": "Miami FL",
    "miami fl": "Miami FL",
    "miami hurricanes": "Miami FL",
    "miami (fl)": "Miami FL",
    "miami (florida) hurricanes": "Miami FL",
    "michigan": "Michigan",
    "michigan wolverines": "Michigan",
    "michigan st": "Michigan St",
    "michigan state": "Michigan St",
    "michigan state spartans": "Michigan St",
    "michigan st spartans": "Michigan St",
    "minnesota": "Minnesota",
    "minnesota golden gophers": "Minnesota",
    "mississippi st": "Mississippi St",
    "mississippi state": "Mississippi St",
    "mississippi state bulldogs": "Mississippi St",
    "nc state": "NC State",
    "nc st": "NC State",
    "ncst": "NC State",
    "n.c. state": "NC State",
    "north carolina state": "NC State",
    "north carolina state wolfpack": "NC State",
    "nc state wolfpack": "NC State",
    "north carolina": "North Carolina",
    "north carolina tar heels": "North Carolina",
    "unc": "North Carolina",
    "unc tar heels": "North Carolina",
    "notre dame": "Notre Dame",
    "notre dame fighting irish": "Notre Dame",
    "ohio st": "Ohio St",
    "ohio st.": "Ohio St",
    "ohio state": "Ohio St",
    "ohio state buckeyes": "Ohio St",
    "ohio st buckeyes": "Ohio St",
    "oklahoma": "Oklahoma",
    "oklahoma sooners": "Oklahoma",
    "oregon": "Oregon",
    "oregon ducks": "Oregon",
    "penn st": "Penn St",
    "penn state": "Penn St",
    "penn state nittany lions": "Penn St",
    "pittsburgh": "Pittsburgh",
    "pittsburgh panthers": "Pittsburgh",
    "purdue": "Purdue",
    "purdue boilermakers": "Purdue",
    "rutgers": "Rutgers",
    "rutgers scarlet knights": "Rutgers",
    "seton hall": "Seton Hall",
    "seton hall pirates": "Seton Hall",
    "st. john's": "St. John's",
    "st. john's red storm": "St. John's",
    "syracuse": "Syracuse",
    "syracuse orange": "Syracuse",
    "tcu": "TCU",
    "tcu horned frogs": "TCU",
    "temple": "Temple",
    "temple owls": "Temple",
    "tennessee": "Tennessee",
    "tennessee lady vols": "Tennessee",
    "texas": "Texas",
    "texas longhorns": "Texas",
    "texas am": "Texas A&M",
    "texas a&m": "Texas A&M",
    "texas a&m aggies": "Texas A&M",
    "texas tech": "Texas Tech",
    "texas tech lady raiders": "Texas Tech",
    "ucla": "UCLA",
    "ucla bruins": "UCLA",
    "usc": "USC",
    "usc trojans": "USC",
    "utah": "Utah",
    "utah utes": "Utah",
    "vanderbilt": "Vanderbilt",
    "vanderbilt commodores": "Vanderbilt",
    "villanova": "Villanova",
    "villanova wildcats": "Villanova",
    "virginia": "Virginia",
    "virginia cavaliers": "Virginia",
    "virginia tech": "Virginia Tech",
    "virginia tech hokies": "Virginia Tech",
    "wake forest": "Wake Forest",
    "wake forest demon deacons": "Wake Forest",
    "washington": "Washington",
    "washington huskies": "Washington",
    "wisconsin": "Wisconsin",
    "wisconsin badgers": "Wisconsin",
    # ── Mid-majors / tournament regulars ────────────────────────────────────
    "akron": "Akron",
    "akron zips": "Akron",
    "california": "California Golden Bears",
    "cal": "California Golden Bears",
    "cal bears": "California Golden Bears",
    "california golden bears": "California Golden Bears",
    "charlotte": "Charlotte 49ers",
    "charlotte 49ers": "Charlotte 49ers",
    "connecticut": "UConn",
    "uconn": "UConn",
    "uconn huskies": "UConn",
    "connecticut huskies": "UConn",
    "dayton": "Dayton",
    "dayton flyers": "Dayton",
    "drake": "Drake",
    "florida a&m": "Florida A&M",
    "florida a&m rattlers": "Florida A&M",
    "george washington": "George Washington",
    "gw": "George Washington",
    "george washington colonials": "George Washington",
    "gonzaga": "Gonzaga",
    "gonzaga bulldogs": "Gonzaga",
    "houston": "Houston",
    "houston cougars": "Houston",
    "iowa st": "Iowa St",
    "iowa state": "Iowa St",
    "iowa state cyclones": "Iowa St",
    "kentucky": "Kentucky",
    "kentucky wildcats": "Kentucky",
    "long beach st": "Long Beach St",
    "long beach state": "Long Beach St",
    "long beach state beach": "Long Beach St",
    "memphis": "Memphis",
    "memphis tigers": "Memphis",
    "miami oh": "Miami OH",
    "miami (oh)": "Miami OH",
    "miami (ohio) redhawks": "Miami OH",
    "michigan st": "Michigan St",
    "michigan state": "Michigan St",
    "michigan state spartans": "Michigan St",
    "mississippi st": "Mississippi St",
    "mississippi state": "Mississippi St",
    "mississippi state bulldogs": "Mississippi St",
    "missouri": "Missouri",
    "missouri tigers": "Missouri",
    "nebraska": "Nebraska",
    "nebraska cornhuskers": "Nebraska",
    "nevada": "Nevada",
    "north carolina central": "North Carolina Central",
    "north carolina central eagles": "North Carolina Central",
    "north texas": "North Texas",
    "north texas mean green": "North Texas",
    "ohio": "Ohio",
    "ohio bobcats": "Ohio",
    "ole miss": "Ole Miss",
    "ole miss rebels": "Ole Miss",
    "rhode island": "Rhode Island",
    "saint joseph's": "Saint Joseph's",
    "saint joseph's hawks": "Saint Joseph's",
    "saint louis": "Saint Louis",
    "saint louis billikens": "Saint Louis",
    "saint mary's": "Saint Mary's",
    "san diego st": "San Diego St",
    "san diego state": "San Diego St",
    "san diego state aztecs": "San Diego St",
    "south carolina": "South Carolina",
    "south carolina gamecocks": "South Carolina",
    "south florida": "South Florida",
    "stanford": "Stanford",
    "stanford cardinal": "Stanford",
    "st. bonaventure": "St. Bonaventure",
    "st. bonaventure bonnies": "St. Bonaventure",
    "toledo": "Toledo",
    "toledo rockets": "Toledo",
    "tulane": "Tulane",
    "tulane green wave": "Tulane",
    "uab": "UAB",
    "uab blazers": "UAB",
    "ucf": "UCF",
    "ucf knights": "UCF",
    "umass": "UMass",
    "massachusetts": "UMass",
    "umass minutewomen": "UMass",
    "utah st": "Utah St",
    "utah state": "Utah St",
    "utah state aggies": "Utah St",
    "vcu": "VCU",
    "vcu rams": "VCU",
    "wichita st": "Wichita St",
    "wichita state": "Wichita St",
    "wichita state shockers": "Wichita St",
    "xavier": "Xavier",
    "xavier musketeers": "Xavier",
}
